### ISSUE TITLE
Fetching tables and views also fetch metadata tables

### ISSUE THREAD

**Issue by sebobr** [firebolt-db/jdbc#123]
Hello, I was testing the 2.2.4-SNAPSHOT version of the connector, and noticed that I have issue with what I am fetching compared to what I am expecting to fetch.

So to be quick, I am opening a connection using DriverManager.getConnection(MY_PARAMS_HERE).
I use the connection to getMetaData() and then getTables() (all method from java.sql DatabaseMetaData interface)
So the result is that I am fetching metadata about my tables and views, but also what seems to be structural tables, namely : 

query_history
running_queries
cache
columns
databases
engines
indexes
running_pipes
service_account_users
tables

Those seems to be metadata tables from Firebolt, and usually with the getTables in other jdbc you only get your own tables and views. Is it an expected behavior or should I use another technique to only get my own tables and views ?

**Comment by aymeric-dispa** [comment]
Hi @sebobr,

It is because you are getting the tables from all the schemas (but you only need the ones with the schema 'public'). You can specify a schema pattern in order to receive the tables you want.

It is an expected behavior (eg, I just tried the following with Postgres and I also receive the tables from other schemas)
`connection.getMetaData().getTables(null, null, null, null )`

The following should work:
`connection.getMetaData().getTables(null, "public", null, null)`

**Comment by sebobr** [comment]
Okay, I didn't realize the tables where located on this schema. It works fine, thanks !
